# Generated by Django 3.2.9 on 2021-11-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
